#nullable enable
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Asterisk.Sdk.Ami.SourceGenerators;

/// <summary>
/// Source generator that creates a FrozenDictionary mapping event type names
/// to factory delegates. Replaces classpath scanning with compile-time discovery.
/// </summary>
[Generator]
public sealed class EventRegistryGenerator : IIncrementalGenerator
{
    private const string AsteriskMappingFqn =
        "Asterisk.Sdk.Attributes.AsteriskMappingAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes decorated with [AsteriskMapping] that inherit from ManagerEvent
        var eventInfos = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AsteriskMappingFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => ExtractEventInfo(ctx, ct))
            .Where(static info => info != null)
            .Select(static (info, _) => info!.Value);

        // Collect all event infos and generate the registry
        var collected = eventInfos.Collect();

        context.RegisterSourceOutput(collected, static (spc, events) =>
        {
            if (events.IsEmpty)
                return;

            var source = GenerateRegistry(events);
            spc.AddSource("GeneratedEventRegistry.g.cs", source);
        });
    }

    private static EventInfo? ExtractEventInfo(
        GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (ctx.TargetSymbol is not INamedTypeSymbol symbol || symbol.IsAbstract)
            return null;

        // Must inherit from ManagerEvent (directly or transitively)
        if (!InheritsFrom(symbol, "Asterisk.Sdk.ManagerEvent"))
            return null;

        // Get the mapping name from the attribute
        var attr = ctx.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == AsteriskMappingFqn);
        if (attr == null || attr.ConstructorArguments.Length == 0)
            return null;

        var mappingName = attr.ConstructorArguments[0].Value as string;
        if (string.IsNullOrEmpty(mappingName))
            return null;

        var fullyQualifiedName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return new EventInfo(mappingName!, fullyQualifiedName);
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, string baseTypeFqn)
    {
        var current = symbol.BaseType;
        while (current != null)
        {
            if (current.ToDisplayString() == baseTypeFqn)
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private static string GenerateRegistry(ImmutableArray<EventInfo> events)
    {
        var sb = new StringBuilder(8192);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Asterisk.Sdk;");
        sb.AppendLine();
        sb.AppendLine("namespace Asterisk.Sdk.Ami.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// AOT-compatible event registry mapping AMI event names to factory delegates.");
        sb.AppendLine("/// Auto-generated by EventRegistryGenerator.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class GeneratedEventRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly FrozenDictionary<string, Func<ManagerEvent>> Registry =");
        sb.AppendLine("        new Dictionary<string, Func<ManagerEvent>>(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("        {");

        // Sort for deterministic output
        var sorted = events.OrderBy(e => e.MappingName).ToArray();
        for (int i = 0; i < sorted.Length; i++)
        {
            var info = sorted[i];
            var comma = i < sorted.Length - 1 ? "," : "";
            sb.AppendLine($"            [\"{EscapeString(info.MappingName)}\"] = static () => new {info.FullyQualifiedTypeName}(){comma}");
        }

        sb.AppendLine("        }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Number of registered event types.</summary>");
        sb.AppendLine($"    public static int Count => Registry.Count;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a new instance of the event class for the given AMI event name.");
        sb.AppendLine("    /// Returns null if the event name is not recognized.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static ManagerEvent? Create(string eventName) =>");
        sb.AppendLine("        Registry.TryGetValue(eventName, out var factory) ? factory() : null;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns true if the given event name is registered.</summary>");
        sb.AppendLine("    public static bool IsKnown(string eventName) =>");
        sb.AppendLine("        Registry.ContainsKey(eventName);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private readonly struct EventInfo
    {
        public readonly string MappingName;
        public readonly string FullyQualifiedTypeName;

        public EventInfo(string mappingName, string fullyQualifiedTypeName)
        {
            MappingName = mappingName;
            FullyQualifiedTypeName = fullyQualifiedTypeName;
        }
    }
}
