services:
  postgres:
    image: postgres:17-alpine
    container_name: functional-postgres
    environment:
      POSTGRES_DB: asterisk
      POSTGRES_USER: asterisk
      POSTGRES_PASSWORD: asterisk
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asterisk"]
      interval: 3s
      timeout: 2s
      retries: 10

  asterisk-realtime:
    image: docker-asterisk-realtime:latest
    container_name: functional-asterisk-realtime
    ports:
      - "15038:5038"
      - "18088:8088"
    volumes:
      - ../asterisk-config-realtime/ari.conf:/etc/asterisk/ari.conf:ro
      - ../asterisk-config-realtime/asterisk.conf:/etc/asterisk/asterisk.conf:ro
      - ../asterisk-config-realtime/cdr.conf:/etc/asterisk/cdr.conf:ro
      - ../asterisk-config-realtime/cdr_odbc.conf:/etc/asterisk/cdr_odbc.conf:ro
      - ../asterisk-config-realtime/cel.conf:/etc/asterisk/cel.conf:ro
      - ../asterisk-config-realtime/cel_odbc.conf:/etc/asterisk/cel_odbc.conf:ro
      - ../asterisk-config-realtime/confbridge.conf:/etc/asterisk/confbridge.conf:ro
      - ../asterisk-config-realtime/extconfig.conf:/etc/asterisk/extconfig.conf:ro
      - ../asterisk-config-realtime/extensions.conf:/etc/asterisk/extensions.conf:ro
      - ../asterisk-config-realtime/features.conf:/etc/asterisk/features.conf:ro
      - ../asterisk-config-realtime/geolocation.conf:/etc/asterisk/geolocation.conf:ro
      - ../asterisk-config-realtime/http.conf:/etc/asterisk/http.conf:ro
      - ../asterisk-config-realtime/logger.conf:/etc/asterisk/logger.conf:ro
      - ../asterisk-config-realtime/manager.conf:/etc/asterisk/manager.conf:ro
      - ../asterisk-config-realtime/modules.conf:/etc/asterisk/modules.conf:ro
      - ../asterisk-config-realtime/musiconhold.conf:/etc/asterisk/musiconhold.conf:ro
      - ../asterisk-config-realtime/pjproject.conf:/etc/asterisk/pjproject.conf:ro
      - ../asterisk-config-realtime/pjsip.conf:/etc/asterisk/pjsip.conf:ro
      - ../asterisk-config-realtime/queues.conf:/etc/asterisk/queues.conf:ro
      - ../asterisk-config-realtime/res_odbc.conf:/etc/asterisk/res_odbc.conf:ro
      - ../asterisk-config-realtime/res_parking.conf:/etc/asterisk/res_parking.conf:ro
      - ../asterisk-config-realtime/sorcery.conf:/etc/asterisk/sorcery.conf:ro
      - ../asterisk-config-realtime/users.conf:/etc/asterisk/users.conf:ro
      - ../asterisk-config-realtime/odbcinst.ini:/etc/odbcinst.ini:ro
      - ../asterisk-config-realtime/odbc.ini:/etc/odbc.ini:ro
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "asterisk", "-rx", "core show version"]
      interval: 5s
      timeout: 3s
      retries: 15
