[modules]
autoload = yes

; Legacy channel drivers not needed
noload = chan_sip.so
noload = chan_skinny.so
noload = chan_mgcp.so

; Database drivers not needed for tests
noload = res_config_odbc.so
noload = res_odbc.so
noload = res_config_ldap.so
noload = res_config_sqlite3.so
noload = res_config_pgsql.so
