[general]
persistentmembers = no

[test-queue]
musicclass = default
strategy = ringall
timeout = 15
retry = 5
wrapuptime = 0
maxlen = 10

[test-queue-2]
musicclass = default
strategy = ringall
timeout = 15
retry = 5
wrapuptime = 0
maxlen = 10
