using System.Runtime.CompilerServices;

namespace Verbara.Sdk.Governance.Tests;

/// <summary>
/// Locates the repo's <c>src/</c> tree (anchored off this file's compile-time path so it works
/// regardless of the working directory or CI layout) and enumerates the real product source files
/// and project files, excluding build output and generated code. The <c>src/</c> counterpart of
/// <see cref="TestTreeSource"/>.
/// </summary>
internal static class SrcTreeSource
{
    private const string SolutionFile = "Verbara.Sdk.slnx";

    private static readonly string[] GeneratedSuffixes =
    [
        ".g.cs",
        ".Designer.cs",
        ".generated.cs",
    ];

    /// <summary>
    /// Locates the repo root (the directory containing <c>Verbara.Sdk.slnx</c>) and returns its
    /// <c>src/</c> folder. Walks up from <see cref="AppContext.BaseDirectory"/> first — a RUNTIME
    /// path (<c>Tests/&lt;proj&gt;/bin/&lt;cfg&gt;/&lt;tfm&gt;</c>) that is immune to
    /// deterministic-build path mapping — then falls back to this file's compile-time path.
    /// (This repo sets <c>ContinuousIntegrationBuild=true</c> in CI, so <c>[CallerFilePath]</c>
    /// is remapped to the non-existent <c>/_/…</c> there; a caller-path-only locator does not
    /// survive that.) Throws if the root cannot be located, so a path regression fails loudly
    /// instead of silently scanning nothing.
    /// </summary>
    public static string SrcRoot([CallerFilePath] string callerPath = "")
    {
        return TryWalkUp(AppContext.BaseDirectory)
            ?? TryWalkUp(Path.GetDirectoryName(callerPath))
            ?? throw new InvalidOperationException(
                $"Could not locate '{SolutionFile}' walking up from '{AppContext.BaseDirectory}' " +
                $"or '{callerPath}'. The governance guard cannot find the repo's src/ tree.");
    }

    private static string? TryWalkUp(string? start)
    {
        if (string.IsNullOrEmpty(start))
            return null;

        var dir = new DirectoryInfo(start);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, SolutionFile)))
                return Path.Combine(dir.FullName, "src");

            dir = dir.Parent;
        }

        return null;
    }

    /// <summary>
    /// Enumerates every real product source file under <see cref="SrcRoot"/>, excluding:
    /// any path with an <c>obj</c>/<c>bin</c> segment, generated filenames
    /// (<c>.g.cs</c>/<c>.Designer.cs</c>/<c>.generated.cs</c>), and files whose first 3 lines
    /// carry an <c>&lt;auto-generated</c> banner.
    /// </summary>
    public static IEnumerable<string> EnumerateSrcSources()
    {
        var root = SrcRoot();
        foreach (var file in Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories))
        {
            if (HasExcludedSegment(file))
                continue;
            if (HasGeneratedSuffix(file))
                continue;
            if (LooksAutoGenerated(file))
                continue;

            yield return file;
        }
    }

    /// <summary>
    /// Enumerates every real product project file under <see cref="SrcRoot"/>, excluding any path
    /// with an <c>obj</c>/<c>bin</c> segment.
    /// </summary>
    public static IEnumerable<string> EnumerateSrcProjects()
    {
        var root = SrcRoot();
        foreach (var file in Directory.EnumerateFiles(root, "*.csproj", SearchOption.AllDirectories))
        {
            if (HasExcludedSegment(file))
                continue;

            yield return file;
        }
    }

    private static bool HasExcludedSegment(string path)
    {
        var segments = path.Split(Path.DirectorySeparatorChar);
        foreach (var segment in segments)
        {
            if (segment is "obj" or "bin")
                return true;
        }

        return false;
    }

    private static bool HasGeneratedSuffix(string path)
    {
        var fileName = Path.GetFileName(path);
        foreach (var suffix in GeneratedSuffixes)
        {
            if (fileName.EndsWith(suffix, StringComparison.Ordinal))
                return true;
        }

        return false;
    }

    private static bool LooksAutoGenerated(string path)
    {
        using var reader = new StreamReader(path);
        for (var i = 0; i < 3; i++)
        {
            var line = reader.ReadLine();
            if (line is null)
                break;
            if (line.Contains("<auto-generated", StringComparison.Ordinal))
                return true;
        }

        return false;
    }
}
