[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[2000]
type = endpoint
context = test-functional
disallow = all
allow = ulaw
auth = 2000-auth
aors = 2000-aors

[2000-auth]
type = auth
auth_type = userpass
password = 2000
username = 2000

[2000-aors]
type = aor
max_contacts = 1
