[general]

[test-queue]
strategy = ringall
timeout = 15
wrapuptime = 0
joinempty = yes
leavewhenempty = no

[test-queue-2]
strategy = ringall
timeout = 15
wrapuptime = 0
joinempty = yes
leavewhenempty = no

[test-queue-3]
strategy = ringall
timeout = 15
wrapuptime = 0
joinempty = yes
leavewhenempty = no
