; Answering Machine Detection - valores de produccion
[general]
total_analysis_time = 8000
silence_threshold = 256
initial_silence = 2500
after_greeting_silence = 800
greeting = 1300
min_word_length = 90
between_words_silence = 40
maximum_number_of_words = 2
maximum_word_length = 5000
