FROM andrius/asterisk:22

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates libopus0 \
    && rm -rf /var/lib/apt/lists/* \
    && cd /tmp \
    && curl -fsSL https://downloads.digium.com/pub/telephony/codec_opus/asterisk-22.0/x86-64/codec_opus-22.0_1.3.0-x86_64.tar.gz -o codec_opus.tar.gz \
    && tar xzf codec_opus.tar.gz \
    && cp codec_opus-22.0_1.3.0-x86_64/codec_opus.so /usr/lib/asterisk/modules/ \
    && cp codec_opus-22.0_1.3.0-x86_64/format_ogg_opus.so /usr/lib/asterisk/modules/ \
    && rm -rf codec_opus.tar.gz codec_opus-22.0_1.3.0-x86_64 \
    && mkdir -p /var/lib/asterisk/sounds/en \
    && cd /var/lib/asterisk/sounds/en \
    && curl -fsSL https://downloads.asterisk.org/pub/telephony/sounds/asterisk-core-sounds-en-ulaw-current.tar.gz | tar xz \
    && curl -fsSL https://downloads.asterisk.org/pub/telephony/sounds/asterisk-core-sounds-en-gsm-current.tar.gz | tar xz \
    && curl -fsSL https://downloads.asterisk.org/pub/telephony/sounds/asterisk-core-sounds-en-sln16-current.tar.gz | tar xz \
    && curl -fsSL https://downloads.asterisk.org/pub/telephony/sounds/asterisk-extra-sounds-en-ulaw-current.tar.gz | tar xz \
    && curl -fsSL https://downloads.asterisk.org/pub/telephony/sounds/asterisk-extra-sounds-en-gsm-current.tar.gz | tar xz \
    && curl -fsSL https://downloads.asterisk.org/pub/telephony/sounds/asterisk-extra-sounds-en-sln16-current.tar.gz | tar xz \
    && mkdir -p /var/lib/asterisk/sounds/es \
    && cd /var/lib/asterisk/sounds/es \
    && curl -fsSL https://downloads.asterisk.org/pub/telephony/sounds/asterisk-core-sounds-es-ulaw-current.tar.gz | tar xz \
    && curl -fsSL https://downloads.asterisk.org/pub/telephony/sounds/asterisk-core-sounds-es-gsm-current.tar.gz | tar xz \
    && curl -fsSL https://downloads.asterisk.org/pub/telephony/sounds/asterisk-core-sounds-es-sln16-current.tar.gz | tar xz \
    && chown -R asterisk:asterisk /var/lib/asterisk/sounds

COPY entrypoint-asterisk.sh /entrypoint-asterisk.sh
RUN chmod 755 /entrypoint-asterisk.sh

USER asterisk
ENTRYPOINT ["/entrypoint-asterisk.sh"]
