[settings]
ps_endpoints => pgsql,general,ps_endpoints
ps_auths => pgsql,general,ps_auths
ps_aors => pgsql,general,ps_aors
ps_contacts => pgsql,general,ps_contacts
ps_registrations => pgsql,general,ps_registrations
ps_domain_aliases => pgsql,general,ps_domain_aliases
ps_endpoint_id_ips => pgsql,general,ps_endpoint_id_ips

queues => pgsql,general,queue_table
queue_members => pgsql,general,queue_members
