[general]
enabled = yes
bindaddr = 0.0.0.0
port = 5038

[dashboard]
secret = dashboard
read = system,call,agent,user,config,originate,reporting,command,dtmf,cdr
write = system,call,agent,user,config,originate,command,reporting
deny = 0.0.0.0/0.0.0.0
permit = 0.0.0.0/0.0.0.0
